version: "3.3"
services:
  app:
    image: registry.gitlab.com/lema_ufpb/projetos/apps/app-saego-sebtt
    container_name: app-saego-sebtt
    hostname: saego-sebtt
    restart: "unless-stopped"
networks: 
  default: 
    external: 
      name: production 
